In [41]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/startup-logistic-regression/50_Startups.csv


In [42]:
data = pd.read_csv(os.path.join(dirname, "50_Startups.csv"))

In [43]:
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [44]:
from sklearn import preprocessing

In [45]:
le = preprocessing.LabelEncoder()

In [46]:
country = data.iloc[:,3:4].values

In [47]:
country[:,0] = le.fit_transform(data.iloc[:,3:4])

/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [48]:
country

array([[2],
       [0],
       [1],
       [2],
       [1],
       [2],
       [0],
       [1],
       [2],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [2],
       [0],
       [2],
       [1],
       [2],
       [0],
       [2],
       [1],
       [1],
       [2],
       [0],
       [1],
       [2],
       [1],
       [2],
       [1],
       [2],
       [0],
       [1],
       [0],
       [2],
       [1],
       [0],
       [2],
       [0],
       [0],
       [1],
       [0],
       [2],
       [0],
       [2],
       [1],
       [0],
       [2],
       [0]], dtype=object)

In [49]:
ohe = preprocessing.OneHotEncoder()

In [50]:
country = ohe.fit_transform(country).toarray()

In [51]:
country

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0

In [52]:
sonuc = pd.DataFrame(data=country, index=range(50), columns=['CA','FL','NY'])
sonuc

CA   FL   NY
0   0.0  0.0  1.0
1   1.0  0.0  0.0
2   0.0  1.0  0.0
3   0.0  0.0  1.0
4   0.0  1.0  0.0
5   0.0  0.0  1.0
6   1.0  0.0  0.0
7   0.0  1.0  0.0
8   0.0  0.0  1.0
9   1.0  0.0  0.0
10  0.0  1.0  0.0
11  1.0  0.0  0.0
12  0.0  1.0  0.0
13  1.0  0.0  0.0
14  0.0  1.0  0.0
15  0.0  0.0  1.0
16  1.0  0.0  0.0
17  0.0  0.0  1.0
18  0.0  1.0  0.0
19  0.0  0.0  1.0
20  1.0  0.0  0.0
21  0.0  0.0  1.0
22  0.0  1.0  0.0
23  0.0  1.0  0.0
24  0.0  0.0  1.0
25  1.0  0.0  0.0
26  0.0  1.0  0.0
27  0.0  0.0  1.0
28  0.0  1.0  0.0
29  0.0  0.0  1.0
30  0.0  1.0  0.0
31  0.0  0.0  1.0
32  1.0  0.0  0.0
33  0.0  1.0  0.0
34  1.0  0.0  0.0
35  0.0  0.0  1.0
36  0.0  1.0  0.0
37  1.0  0.0  0.0
38  0.0  0.0  1.0
39  1.0  0.0  0.0
40  1.0  0.0  0.0
41  0.0  1.0  0.0
42  1.0  0.0  0.0
43  0.0  0.0  1.0
44  1.0  0.0  0.0
45  0.0  0.0  1.0
46  0.0  1.0  0.0
47  1.0  0.0  0.0
48  0.0  0.0  1.0
49  1.0  0.0  0.0

In [53]:
latestdata = pd.concat([sonuc,data.iloc[:,0:3]],axis = 1)
latestdata

CA   FL   NY  R&D Spend  Administration  Marketing Spend
0   0.0  0.0  1.0  165349.20       136897.80        471784.10
1   1.0  0.0  0.0  162597.70       151377.59        443898.53
2   0.0  1.0  0.0  153441.51       101145.55        407934.54
3   0.0  0.0  1.0  144372.41       118671.85        383199.62
4   0.0  1.0  0.0  142107.34        91391.77        366168.42
5   0.0  0.0  1.0  131876.90        99814.71        362861.36
6   1.0  0.0  0.0  134615.46       147198.87        127716.82
7   0.0  1.0  0.0  130298.13       145530.06        323876.68
8   0.0  0.0  1.0  120542.52       148718.95        311613.29
9   1.0  0.0  0.0  123334.88       108679.17        304981.62
10  0.0  1.0  0.0  101913.08       110594.11        229160.95
11  1.0  0.0  0.0  100671.96        91790.61        249744.55
12  0.0  1.0  0.0   93863.75       127320.38        249839.44
13  1.0  0.0  0.0   91992.39       135495.07        252664.93
14  0.0  1.0  0.0  119943.24       156547.42        256512.92
15  0.0  0.0  1.0  114523.61       122616.84        261776.23
16  1.0  0.0  0.0   78013.11       121597.55        264346.06
17  0.0  0.0  1.0   94657.16       145077.58        282574.31
18  0.0  1.0  0.0   91749.16       114175.79        294919.57
19  0.0  0.0  1.0   86419.70       153514.11             0.00
20  1.0  0.0  0.0   76253.86       113867.30        298664.47
21  0.0  0.0  1.0   78389.47       153773.43        299737.29
22  0.0  1.0  0.0   73994.56       122782.75        303319.26
23  0.0  1.0  0.0   67532.53       105751.03        304768.73
24  0.0  0.0  1.0   77044.01        99281.34        140574.81
25  1.0  0.0  0.0   64664.71       139553.16        137962.62
26  0.0  1.0  0.0   75328.87       144135.98        134050.07
27  0.0  0.0  1.0   72107.60       127864.55        353183.81
28  0.0  1.0  0.0   66051.52       182645.56        118148.20
29  0.0  0.0  1.0   65605.48       153032.06        107138.38
30  0.0  1.0  0.0   61994.48       115641.28         91131.24
31  0.0  0.0  1.0   61136.38       152701.92         88218.23
32  1.0  0.0  0.0   63408.86       129219.61         46085.25
33  0.0  1.0  0.0   55493.95       103057.49        214634.81
34  1.0  0.0  0.0   46426.07       157693.92        210797.67
35  0.0  0.0  1.0   46014.02        85047.44        205517.64
36  0.0  1.0  0.0   28663.76       127056.21        201126.82
37  1.0  0.0  0.0   44069.95        51283.14        197029.42
38  0.0  0.0  1.0   20229.59        65947.93        185265.10
39  1.0  0.0  0.0   38558.51        82982.09        174999.30
40  1.0  0.0  0.0   28754.33       118546.05        172795.67
41  0.0  1.0  0.0   27892.92        84710.77        164470.71
42  1.0  0.0  0.0   23640.93        96189.63        148001.11
43  0.0  0.0  1.0   15505.73       127382.30         35534.17
44  1.0  0.0  0.0   22177.74       154806.14         28334.72
45  0.0  0.0  1.0    1000.23       124153.04          1903.93
46  0.0  1.0  0.0    1315.46       115816.21        297114.46
47  1.0  0.0  0.0       0.00       135426.92             0.00
48  0.0  0.0  1.0     542.05        51743.15             0.00
49  1.0  0.0  0.0       0.00       116983.80         45173.06

In [54]:
latestdata = pd.concat([latestdata,data.iloc[:,-1]],axis = 1)
latestdata

CA   FL   NY  R&D Spend  Administration  Marketing Spend     Profit
0   0.0  0.0  1.0  165349.20       136897.80        471784.10  192261.83
1   1.0  0.0  0.0  162597.70       151377.59        443898.53  191792.06
2   0.0  1.0  0.0  153441.51       101145.55        407934.54  191050.39
3   0.0  0.0  1.0  144372.41       118671.85        383199.62  182901.99
4   0.0  1.0  0.0  142107.34        91391.77        366168.42  166187.94
5   0.0  0.0  1.0  131876.90        99814.71        362861.36  156991.12
6   1.0  0.0  0.0  134615.46       147198.87        127716.82  156122.51
7   0.0  1.0  0.0  130298.13       145530.06        323876.68  155752.60
8   0.0  0.0  1.0  120542.52       148718.95        311613.29  152211.77
9   1.0  0.0  0.0  123334.88       108679.17        304981.62  149759.96
10  0.0  1.0  0.0  101913.08       110594.11        229160.95  146121.95
11  1.0  0.0  0.0  100671.96        91790.61        249744.55  144259.40
12  0.0  1.0  0.0   93863.75       127320.38        249839.44  141585.52
13  1.0  0.0  0.0   91992.39       135495.07        252664.93  134307.35
14  0.0  1.0  0.0  119943.24       156547.42        256512.92  132602.65
15  0.0  0.0  1.0  114523.61       122616.84        261776.23  129917.04
16  1.0  0.0  0.0   78013.11       121597.55        264346.06  126992.93
17  0.0  0.0  1.0   94657.16       145077.58        282574.31  125370.37
18  0.0  1.0  0.0   91749.16       114175.79        294919.57  124266.90
19  0.0  0.0  1.0   86419.70       153514.11             0.00  122776.86
20  1.0  0.0  0.0   76253.86       113867.30        298664.47  118474.03
21  0.0  0.0  1.0   78389.47       153773.43        299737.29  111313.02
22  0.0  1.0  0.0   73994.56       122782.75        303319.26  110352.25
23  0.0  1.0  0.0   67532.53       105751.03        304768.73  108733.99
24  0.0  0.0  1.0   77044.01        99281.34        140574.81  108552.04
25  1.0  0.0  0.0   64664.71       139553.16        137962.62  107404.34
26  0.0  1.0  0.0   75328.87       144135.98        134050.07  105733.54
27  0.0  0.0  1.0   72107.60       127864.55        353183.81  105008.31
28  0.0  1.0  0.0   66051.52       182645.56        118148.20  103282.38
29  0.0  0.0  1.0   65605.48       153032.06        107138.38  101004.64
30  0.0  1.0  0.0   61994.48       115641.28         91131.24   99937.59
31  0.0  0.0  1.0   61136.38       152701.92         88218.23   97483.56
32  1.0  0.0  0.0   63408.86       129219.61         46085.25   97427.84
33  0.0  1.0  0.0   55493.95       103057.49        214634.81   96778.92
34  1.0  0.0  0.0   46426.07       157693.92        210797.67   96712.80
35  0.0  0.0  1.0   46014.02        85047.44        205517.64   96479.51
36  0.0  1.0  0.0   28663.76       127056.21        201126.82   90708.19
37  1.0  0.0  0.0   44069.95        51283.14        197029.42   89949.14
38  0.0  0.0  1.0   20229.59        65947.93        185265.10   81229.06
39  1.0  0.0  0.0   38558.51        82982.09        174999.30   81005.76
40  1.0  0.0  0.0   28754.33       118546.05        172795.67   78239.91
41  0.0  1.0  0.0   27892.92        84710.77        164470.71   77798.83
42  1.0  0.0  0.0   23640.93        96189.63        148001.11   71498.49
43  0.0  0.0  1.0   15505.73       127382.30         35534.17   69758.98
44  1.0  0.0  0.0   22177.74       154806.14         28334.72   65200.33
45  0.0  0.0  1.0    1000.23       124153.04          1903.93   64926.08
46  0.0  1.0  0.0    1315.46       115816.21        297114.46   49490.75
47  1.0  0.0  0.0       0.00       135426.92             0.00   42559.73
48  0.0  0.0  1.0     542.05        51743.15             0.00   35673.41
49  1.0  0.0  0.0       0.00       116983.80         45173.06   14681.40

In [55]:
from sklearn.model_selection import train_test_split

In [56]:
x_train, x_test, y_train, y_test = train_test_split(latestdata2.iloc[:,:-1],latestdata2.iloc[:,-1:],test_size=0.33, random_state=0)

In [57]:
from sklearn.linear_model import LinearRegression

In [58]:
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [59]:
y_pred = regressor.predict(x_test)
y_pred

array([[206160.48445158],
       [285953.11237243],
       [351905.89322476],
       [207175.17548819],
       [477214.60605675],
       [174981.02226582],
       [112680.7512454 ],
       [127894.45291922],
       [277692.5572504 ],
       [460229.7691979 ],
       [253369.5264199 ],
       [154082.22298156],
       [261628.62332516],
       [104010.29012573],
       [325653.02450406],
       [385047.37307506],
       [351713.82275933]])

In [60]:
y_test

Marketing Spend
28        118148.20
11        249744.55
10        229160.95
41        164470.71
2         407934.54
27        353183.81
38        185265.10
31         88218.23
22        303319.26
4         366168.42
33        214634.81
35        205517.64
26        134050.07
34        210797.67
18        294919.57
7         323876.68
14        256512.92

In [61]:
from sklearn.metrics import r2_score

In [62]:
score = r2_score(y_test , y_pred)
score

0.05691181639784748